//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvansDiary.Web.Diary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Hospital {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Hospital() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvansDiary.Web.Diary.Resources.Hospital", typeof(Hospital).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I seem to remember having a niggling tummy ache in the morning but this all stated at lunchtime. I groaned to Emma about having a rough tummy complaining that I really wasn&apos;t due on yet but didn&apos;t think much of it. My usual routine with period pain is to make myself a hot water bottle and curl up with a cup of coffee and that&apos;s exactly what I did. I made a coffee and grabbed myself and kitkat and took it upstairs. I had a feeling this was gonna be a bitch of a period so I changed out of my jeans into my tra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DayOne {
            get {
                return ResourceManager.GetString("DayOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #Post-Op
        ///
        ///I was returned to the ward at 7am. I don&apos;t remember much this day, I was asleep most of the day and I can&apos;t really remember Emma and Evan being there just about all day.  
        ///
        ///Usually the first few hours post-op are groggy but patients slowly recover during the day and are sometimes sitting up or even moving around by the end of the day. Emma says she knew I wasn&apos;t getting better and was really worried about me when she went home. _She called my mother for support and that in turn brought forward [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DayTwo {
            get {
                return ResourceManager.GetString("DayTwo", resourceCulture);
            }
        }
    }
}
