//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvansDiary.Web.Diary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Hospital {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Hospital() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvansDiary.Web.Diary.Resources.Hospital", typeof(Hospital).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###Breathing Improvement
        ///
        ///Until now I had been on 70% Oxygen with the mask. Even though I was awake and seemingly better, the fact that I needed so much Oxygen just to breathe was worrying. Apparently they had tried to drop it lower in the night and my sats (Oxygen Saturation) had dropped. In the morning they lowered to 60% and my sats remained stable. A step in the right direction if still a long way to go.  
        ///
        ///###Oh Poo!
        ///
        ///The previous day I had eaten some solid(ish) food for the first time - a little [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DayEight {
            get {
                return ResourceManager.GetString("DayEight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###And I&apos;m Feeling Great...
        ///
        ///Despite only four hours sleep I woke up feeling good! Laura and Leanne in the beds next to me and opposite were chatting and I joined in and had a cup of coffee. Even before I got up I could really feel the difference, I was going home today.  
        ///
        ///###Shower Time, Yeah Baby!
        ///
        ///After a crappy breakfast I decided to really freshen up and have a shower. The hospital was able to supply me with shampoo and shower gel which was handy because I didn&apos;t have any of that kind of stuff w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DayEleven {
            get {
                return ResourceManager.GetString("DayEleven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *hello??*
        ///
        ///###(Written by Emma)
        ///
        ///This was probably the worst day of all for me. I had felt in control since Thursday and today Caroline&apos;s mum had arrived because she was ever so worried and she wanted to be able to visit Caroline everyday. I wasn&apos;t able to go to the hospital in the day because you are restricted to two visitors and today Caroline&apos;s mum and her brother Herve went. I spent the day with Evan at home. We made a collage of Caroline&apos;s pictures so that we could see her all the time and Evan ac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DayFive {
            get {
                return ResourceManager.GetString("DayFive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *huh?*
        ///
        ///###(Written by Emma)
        ///
        ///Last night we left Caroline just before she was going off to the CT Lab. I did return later that evening (twice) with my mum. I am so glad I had my mum with me as none of us were still expecting Caroline to be intubated. The Doctors hadn&apos;t told us that she would likely remain intubated until her condition stabilised.  
        ///
        ///She looked far more peaceful being intubated as she was just in what the Doctors described as a happy sleepy place. I cried when I saw her, you see stuff  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DayFour {
            get {
                return ResourceManager.GetString("DayFour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###Full English Please!
        ///
        ///I felt pretty good Friday morning and although I wasn&apos;t exactly looking forward to going back to the ward (so boring), I was pleased because I knew how much better I was and it also meant the end of being restricted by so many drips and lines.  
        ///
        ///Laura had done her third night shift in a row. She was by far my favourite nurse :) I felt hungry in the morning and she said that I could get a cooked breakfast from the kitchens and this I did! Sausage, bacon, egg, hash brown, beans a [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DayNine {
            get {
                return ResourceManager.GetString("DayNine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I seem to remember having a niggling tummy ache in the morning but this all stated at lunchtime. I groaned to Emma about having a rough tummy complaining that I really wasn&apos;t due on yet but didn&apos;t think much of it. My usual routine with period pain is to make myself a hot water bottle and curl up with a cup of coffee and that&apos;s exactly what I did. I made a coffee and grabbed myself and kitkat and took it upstairs. I had a feeling this was gonna be a bitch of a period so I changed out of my jeans into my tra [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DayOne {
            get {
                return ResourceManager.GetString("DayOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###On the Mend at Last!
        ///
        ///I&apos;d had a rough night - I found it very difficult to sleep with the oxygen mask because the gas was cold on my face and it also blew into my eyes. Plus the discomfort of hardly being able to move and there was stuff going on in the ITU all night long - nurses milling about, alarms going off, being given drips, checks etc. Ugh!  
        ///
        ///But still, I was awake and on the mend. I had some very exciting news that morning - I was going to have a shampoo!! Seriously, I was pleased about thi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DaySeven {
            get {
                return ResourceManager.GetString("DaySeven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###Out of CT
        ///
        ///I awoke from CT *(pah!)* to find a very uncomfortable tube down my throat, my lips were sore and numb, and course I couldn&apos;t speak. No change there then. Some nurses were around. *&quot;Hi Caroline, it&apos;s Tuesday&quot;*. What the fuck?? Where the hell did the weekend just go? I went down to CT on Saturday!!! Man if you&apos;ve never lost time like that let me tell you what a head-screw it is!  
        ///
        ///I had either Emma or Mum with me, I don&apos;t remember which. I know I spent a lot of time with Emma that afternoon [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DaySix {
            get {
                return ResourceManager.GetString("DaySix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###A Bloody Awakening
        ///
        ///After finally managing to get back off to sleep again I was rudely awakened by the nurse at only 6am, she was giving me blood! I was to be given two units of blood. Apparently the main reason that my sats weren&apos;t quite tip-top was that my haemoglobin levels were low and that was restricting the oxygen I could take in.  
        ///
        ///The blood needed around 2 hours per bag and it was a thick ol&apos; tube so I was a bit restricted. I sat up so I could read and I must have dislodged the line. The nu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DayTen {
            get {
                return ResourceManager.GetString("DayTen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###Something has gone wrong!
        ///
        ///I had a hard night. I was feeling like crap and by the early hours of the morning I was convinced I couldn&apos;t breathe. I called the nurse who propped me up in bed and seemed to just leave me there. Something was seriously up with my chest.  
        ///
        ///Turns out that she hadn&apos;t left me there - she had called the intensive care unit! I was suddenly surrounded by three scary looking doctors all having a good prod. I didn&apos;t really know where I was going - I was dazed. I was hooked up to  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DayThree {
            get {
                return ResourceManager.GetString("DayThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ###Post-Op
        ///
        ///I was returned to the ward at 7am. I don&apos;t remember much this day, I was asleep most of the day and I can&apos;t really remember Emma and Evan being there just about all day.  
        ///
        ///Usually the first few hours post-op are groggy but patients slowly recover during the day and are sometimes sitting up or even moving around by the end of the day. Emma says she knew I wasn&apos;t getting better and was really worried about me when she went home. *She called my mother for support and that in turn brought forwa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DayTwo {
            get {
                return ResourceManager.GetString("DayTwo", resourceCulture);
            }
        }
    }
}
