//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvansDiary.Web.Diary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Year2005 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Year2005() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvansDiary.Web.Diary.Resources.Year2005", typeof(Year2005).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My experience of the birth is totally different to that of Caroline&apos;s. When I think back, parts of it are now starting to blur and I need reminding from those that were present to relive certain events. I guess the pain relief through drugs and that of my natural pain relief are part of the reasons for me not remembering it. I personally handled being pregnant and going through the labour better than I would have handled being the partner who felt completely helpless at times.
        ///    
        ///For two days I was havi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w0One {
            get {
                return ResourceManager.GetString("y1w0One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching your loved one go through the pain of labour when there is virtually nothing you can do to alleviate her pain is heart-wrenching. As the labour drags on and on sapping every ounce of her energy and Christmas Day fades into Boxing day it&apos;s hard to imagine that this little baby will ever actually be born...  
        ///    
        ///The first signs of labour started early on the morning of Christmas Eve. Emma&apos;s waters appeared to break so she phoned the hospital and they advised her to come in due to risk of infectio [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w0Two {
            get {
                return ResourceManager.GetString("y1w0Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My little boy is growing ever so quickly, we went to see his grandma this week as it&apos;s been 5 weeks since our last visit and she couldn&apos;t believe how much he had changed. He has pretty much out grown most of his clothes so we&apos;re washing daily just to make sure he has something to wear. His clothes and toys allowance will definitely be spent on the former this month!  
        ///
        ///I took Evan to see my work colleagues for the first time this week. He was on his best behaviour, he played, smiled, let people hold him a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w10One {
            get {
                return ResourceManager.GetString("y1w10One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;re starting to be able to see some developmental changes in Evan&apos;s behaviour now. He&apos;s been sucking at his fist for a week or two already but sometimes he manages to be a little more dextrous and actually put his fingers in his mouth and suck those. He hasn&apos;t quite found his thumb yet though!  
        ///
        ///He&apos;s also talking *(making word like noises)* a lot more now. He started saying *&quot;gurrr&quot;* a lot a couple of weeks back but now he has a new gurgle where he really sounds like he&apos;s trying to laugh and he tends t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w10Two {
            get {
                return ResourceManager.GetString("y1w10Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This week the long awaited &quot;Baby Massage&quot; class started, it&apos;s only on for 4 weeks but it&apos;s just another opportunity to get us out of the house for a few hours to see other babies. Doing the little walk to Somerfield on our own is getting a bit boring and I really think it will do Evan good to get out and about more. We&apos;ve been doing massage with Evan for several weeks now so this class was mainly for the social aspect as well as just making sure I am doing it correctly. The class is run free by the local he [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w11One {
            get {
                return ResourceManager.GetString("y1w11One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evan has been exercising his new found vocal chords for a little while now but this week he discovered a new trick. He was lying on the change mat after I&apos;d changed his nappy and I was chatting to Emma and suddenly he just let out this loud shout that really made me jump! We both looked at each other and then at him and he just smiled, cutie.  
        ///
        ///A few weeks ago we had a visit from one of our friends and she had bought us a nice set of baby vests with one for every day of the week. I often see these types  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w11Two {
            get {
                return ResourceManager.GetString("y1w11Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I introduced Evan to a new environment this week, we went to &quot;Teddies Music Club&quot;. Teddies is run once a week and is more suited to children at toddler age as they can interact more. I think it is also good for babies as it gives them new experiences, but they won&apos;t be able to sing along to the songs and do some of the actions, however it gets us out of the house for a little bit. I didn&apos;t realise this, but Evan had never heard anyone clap - hmm, unless me clapping when Spurs score on TV whilst Evan was in  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w12One {
            get {
                return ResourceManager.GetString("y1w12One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ooh we had a bit of a &apos;mare this week - the first time I caused an injury to Evan! There were tears... baby tears, Emma tears and there were screams! How did this happen? Well it all started with some baby fingernails and a pair of clippers :/ I&apos;m sure you can guess the rest!  
        ///
        ///Due to the little &quot;jazz hands&quot; thing he tends to do when he&apos;s feeding *(see the piccy in week 6)* it&apos;s usually quite easy to trim his nails as he&apos;s fairly relaxed and sleepy when he&apos;s been feeding for a while and he splays his fin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w12Two {
            get {
                return ResourceManager.GetString("y1w12Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This week I introduced Evan to his cardboard books. He hasn&apos;t figured out how to hold them or eat them but he does like to look at the pictures. He woke me up at 6am one day this week and showed no signs of wanting to go back to sleep so we made a coffee for mummy and I plonked him in between my legs so that he was able to sit up. My legs were supporting him on both sides and from that position we sat and read all about racing cars and also about Little Bear&apos;s adventures. I&apos;ve read that babies do like to ha [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w13One {
            get {
                return ResourceManager.GetString("y1w13One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over the last few weeks Evan has started to chew things more. He started off mainly chewing his fist *(which he still does - a lot!)* but now he&apos;s started chewing everything else too - his toys, his clothes, and his muslin! He&apos;s taken quite a liking to his muslin and he buries his face in it and giggles! We discovered this week that it will actually keep him amused for quite a while!  
        ///
        ///Another discovery we made this week is that Evan has started showing an interest in the TV. Is that normal for young bab [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w13Two {
            get {
                return ResourceManager.GetString("y1w13Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This week Evan had another trip to the injection nurse! I wasn&apos;t looking forward to this because I still had images of what happened last time. Caroline came with us this time to make sure we were both ok :). He had to sit on my lap instead of lying on the bed and it was probably for the best because I didn&apos;t see his face when he cried so it didn&apos;t make me cry. I had to hold his leg down for the nurse, which wasn&apos;t what I really wanted to do, I just wanted to be able to comfort him. Caroline let him hold he [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w14One {
            get {
                return ResourceManager.GetString("y1w14One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emma already mentioned that Evan has a new trick of arching up his back. Sometimes this can be a real nuisance. A few days ago we had him in the pushchair while we were eating dinner. It was tilted upwards and we hadn&apos;t strapped him in *(never needed to before)*. Suddenly he started to arch his back and wiggled so much that I actually thought he was going to fall out! Now he gets strapped in everywhere! But one place that we can&apos;t strap him is our laps. He frequently sits on our laps now and watches TV or h [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w14Two {
            get {
                return ResourceManager.GetString("y1w14Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As we mentioned a few weeks ago, Evan is now in the big bath as he is now a big boy! He is even starting to outgrow the bath support that we use there so I am not sure what we will do then. The big bath is helping us all to feel comfortable and prepare for our first swimming session with Evan as he needs to get used to having water on his face. It just so happens that he now gets ever so excited at bath times that this week he has learned that flapping his arms and kicking his feet makes splashes... lots of [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w15One {
            get {
                return ResourceManager.GetString("y1w15One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We had a monumental event this week (kinda) - Evan crawled! Okay so it was backwards, but he still crawled :) I had him on his belly for tummy time on the change mat and he tends to wriggle around a lot these days and I noticed that he was shuffling himself downwards towards the back of the mat! I watched him and sure enough he managed to shuffle all the way back down until his legs were on carpet and he got a bit stuck and I had to slide him back up. He&apos;s done it several times since then.  
        ///
        ///I&apos;ve noticed [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w15Two {
            get {
                return ResourceManager.GetString("y1w15Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I haven&apos;t been able to take Evan to the mother and baby group for the past 2 weeks due to his injections the first Wednesday and then me having a tummy bug last week, so I was really looking forward to weighing him this week. He&apos;s certainly eating well and I knew he had put on some weight because he&apos;s now starting to fit into his 6-9 month clothes and he&apos;s only 3 and a half months old now! The last time I weighed him at week 13 he&apos;d just crossed over the 1 stone mark and Caroline was betting he&apos;d be 15llbs  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w16One {
            get {
                return ResourceManager.GetString("y1w16One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to What&apos;s your worst nightmare when you have a new baby? Well, I suppose there are a million things but one of them might be a washing machine breakdown. Our washing machine has been making strange noises for a while now and it finally packed up at the end of last week. We rushed down to the local store the next morning to buy another one but we had to wait until Thursday for delivery which left us without a machine for almost a week!  
        ///
        ///Now this coupled with our little poo problem is not a Good Thing! For s [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w16Two {
            get {
                return ResourceManager.GetString("y1w16Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This week was the first week that we didn&apos;t see a gain in Evan&apos;s weight. In fact he had actually lost 4 ounces when I weighed him. I spoke to the Health Visitor at the clinic and she said that they don&apos;t like to see a drop in weight but Evan looked really healthy so they would just see how he was when I go to weight him next week.  
        ///
        ///This week at the Mother and Baby group they introduced us to Baby Yoga! It was quite fun and Evan seemed to enjoy it at first but then he got hungry and demanded boob halfway [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w17One {
            get {
                return ResourceManager.GetString("y1w17One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After having spent _**weeks**_ painting Evan&apos;s room while Emma was pregnant Evan finally got to experience it for himself this week! Up until now he had only slept either in the bed with Emma or had little naps in the pram and had never been in his cot!  
        ///
        ///But the time and money has paid off as he seems to like his room and his cot. Some days are better than others of course and there are days when he just screams when we try to put him down to sleep and he can&apos;t calm himself down but most of the time he  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w17Two {
            get {
                return ResourceManager.GetString("y1w17Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caroline returned to University this week and we have really enjoyed having her at home over the past 5 weeks so she was missed - even though she only had to go in for 2 days. I had to cancel a visit to see Evan&apos;s great grandmother in Birmingham again (3rd time now) and I feel really bad as she hasn&apos;t seen him now since he was 6 weeks old.  
        ///
        ///The weather has been really nice this week and we were able to introduce Evan to grass - I think he really liked the feel of it on his bare feet. He does like it out [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w18One {
            get {
                return ResourceManager.GetString("y1w18One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s nice to watch babies grow and develop and learn new things. I remember when Evan was first born and everyone was always saying &quot;Hold his head!&quot; but even then he could lift his head up a little. Now he has far better neck control - around 90% I&apos;d say.  
        ///
        ///Both of us tend to carry him in a similar position - in one arm facing in with his head looking back over our shoulder. I&apos;m left-armed and Emma is right-armed but other than that it&apos;s pretty similar. What we were always finding is that his neck was st [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w18Two {
            get {
                return ResourceManager.GetString("y1w18Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evan was Mr Cool Dude this week :). We had some lovely weather and seeing as it was a bank holiday and the shops would be busy we decided to walk to Mothercare. We both sneezed quite a bit on the way so I do hope he is not going to inherit my hayfever allergies... We borrowed some hats from our friend Sue but Evan has outgrown them already so I decided to splash out on some new hats for my cutie pie and to help with his light sensitivity we have bought him some Baby Banz sunglasses - they look fab!  
        ///
        ///Eva [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w19One {
            get {
                return ResourceManager.GetString("y1w19One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last week I was saying how much better Evan&apos;s neck control is and how he hardly ever lets his head flop down onto us now. Well, he likes to prove me wrong! Evan is a pukey boy - he really could puke for England in the World Puking Olympics if there was such a thing! This week he was up on Emma&apos;s shoulder after a feed and she was giving him his usual pat on the back to wind him when out blurted a couple of gallons of puke! That&apos;s not the best part though - he then plopped his face right down into it! It cove [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w19Two {
            get {
                return ResourceManager.GetString("y1w19Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My recollection of days and times became completely muddled after the birth of Evan. I was wheeled up to the postnatal ward at 7am in the morning and because we then went to bed it actually feels like I was in hospital for a day longer than I actually was. I didn&apos;t get much sleep at all and 2 hours later I woke up feeling terrible. My right leg was still completely dead and I couldn&apos;t move at all. When Evan started to cry I couldn&apos;t tend to him because of my problems with the epidural and I didn&apos;t have a nu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w1One {
            get {
                return ResourceManager.GetString("y1w1One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emma and Evan were taken up to the postnatal ward at about 7am and we were all thoroughly exhausted. Her mum and I waited until they were both settled and then went home for some well-earned sleep! The drive home was weird. It was about -3 outside and the car was frozen solid. To me it was the end of a very long night but in reality the day was just starting. As I started to drive the emotion of it all really hit me and I had tears streaming down my face all the way home. I slumped into bed and managed to g [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w1Two {
            get {
                return ResourceManager.GetString("y1w1Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evan and I attended a new group this week called Twinkles. We have outgrown the new mums group and over the past few weeks the health visitors have been hinting that we might scare off new mums because we all know each other. This new group is for babies and toddlers and it was really busy so at least I know Evan will get the contact with other children that he needs.  
        ///
        ///I still went to the new mums group to attend the weigh in and will probably do so until after I start weaning as I want to ensure that E [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w20One {
            get {
                return ResourceManager.GetString("y1w20One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evan is getting better and sitting up and not only that but he&apos;s starting to stand up too. Of course we have to hold him so he doesn&apos;t fall over but he holds himself up on his legs and straightens out his whole body. Sometimes he&apos;ll even lift a foot as though he&apos;s going to take a step but I think we&apos;re a way off that stage yet...  
        ///
        ///Over the last couple of weeks we&apos;ve been changing Evan&apos;s routine a little bit. We&apos;re trying to get him used to a more regular bed time and being in his cot. One of Emma&apos;s frie [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w20Two {
            get {
                return ResourceManager.GetString("y1w20Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have started to notice these little patches of dry skin appearing on Evan&apos;s body. We managed to get rid of one that he has had for months on his shoulder by applying Sudocrem at every nappy change. However, this little persistent one on the head just refuses to go away so this week I decided to take him to the doctors to find out what it was as I didn&apos;t want it to be on all his baby photos! Our GP thinks Evan may have a mild form of baby eczema so she has given me a prescription for some Canesten cream -  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w21One {
            get {
                return ResourceManager.GetString("y1w21One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evan made a new discovery this week - one I was hoping he wouldn&apos;t make for a little while longer yet - yup, he found his willy!! He&apos;s been getting more adventurous with his hands of late and he can lift his legs right up which tips his pelvis upwards too. He was playing in the bath and suddenly I heard this little scream from Emma - *&quot;Oh No, he&apos;s got his willy!!!!&quot;*. I came running in to have a look and sure enough there he was giving it a good old tug! Looked rather painful to me but what would I know abo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w21Two {
            get {
                return ResourceManager.GetString("y1w21Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We had a lot of new events this week with Evan. He is now exploring further south and now likes to grab his feet and chatter to himself—I&apos;m not sure if he actually knows that it&apos;s himself grabbing those little tootsies. Our evening routine is ticking along nicely and Evan has started falling asleep whilst I read him his bed time story, it must be all the frantic kicking and splashing that has worn him out from his bath earlier. He seems to know whenever his nappy is off now and we had an incident earlier wh [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w22One {
            get {
                return ResourceManager.GetString("y1w22One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earlier this week we had some scorching hot weather and one evening we were sitting in the lounge and Evan was getting so hot that we decided to just strip him off and let him have some nekkid time. There&apos;s just something so scrumptious about a naked baby! We had the patio door open and there was a light breeze so (much to Emma&apos;s disapproval) I took him outside to play in the garden. &quot;Oh he&apos;ll get grass up his bum!!&quot;, she moaned but Evan didn&apos;t seem to mind one bit. He loved it and two of the cats came out  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w22Two {
            get {
                return ResourceManager.GetString("y1w22Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I was very nervous about the idea of weaning Evan and my original plans were to return to work in the summer and Caroline would look after Evan instead. That would have been perfect because Caroline being the cook could prepare all his foods. Now that my plans are different I then realised that I would be around at weaning time and I am actually very glad I didn&apos;t miss this momentous period in Evans development. I actually look forward to feed time and when we get to try him on new foods. I decided to prepa [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w23One {
            get {
                return ResourceManager.GetString("y1w23One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The weaning continues... we&apos;ve introduced two new foods this week - carrot and banana. No, not at the same time! We tried the banana first and that probably wasn&apos;t the best option as it was really difficult to mash properly! It got all lumpy and kinda slimy and this proved quite a problem. Every time we gave him a mouthful that was a bit too lumpy he&apos;d pull thus funny face, make a kind of gagging noise and poke his tongue out. Highly amusing I thought.  
        ///
        ///We thought the banana was tricky; nothing compared [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w23Two {
            get {
                return ResourceManager.GetString("y1w23Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This week we tried some new foods with Evan and also introduced breakfast. We tried Evan on sweet potato and pear, both of which he really liked. We started to do combination meals as well like carrot and sweet potato followed by pear and baby rice for dessert. I have been taken my time with new foods to make sure that Evan doesn&apos;t get overloaded with new flavours. I didn&apos;t want to try something new everyday but give Evan a couple of days to get used to a new flavour. We&apos;ve been trying to film all the new t [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w24One {
            get {
                return ResourceManager.GetString("y1w24One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We had an exciting time this week when we took Evan swimming for the very first time! The local sports centre has a baby pool so we took him there. Emma was very anxious about the whole thing and she held him tightly and just sat in the corner of the pool. At first Evan seemed quite oblivious to the water. He just sat there in her arms chewing his fist and looking around as usual. We were quite surprised because of his antics in the bath.  
        ///
        ///So with a little persuasion I was able to convince Emma to let m [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w24Two {
            get {
                return ResourceManager.GetString("y1w24Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evan saw his grandma several times this week because I really wanted to make use of my free time whilst I am off on maternity leave. I am probably going to have to return to work at the end of the year after all so I have to make sure I enjoy my time with Evan whilst we have it.  
        ///
        ///It felt like Evan&apos;s and my birthday all in one this week. I had plans to buy him a new stroller type buggy now that we are approaching summer as I really wanted to get a pushchair that could be front facing with Evan sitting up [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w25One {
            get {
                return ResourceManager.GetString("y1w25One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evan is sitting up much better now and he likes to reach out to toys nearby when he is sitting up. This is a good thing because I don&apos;t have to have top class reactions times for anticipating when he is going to fall. I tried filming him alone with the camcorder this week and that was a disaster because he wanted to eat it and he was being very playful. I didn&apos;t realise how far away I was from him and when he lost his balance sitting up, he started to fall backwards. I threw out my arm but ended up grasping [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w26One {
            get {
                return ResourceManager.GetString("y1w26One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over the last couple of weeks we&apos;ve been trying to establish more of a routine for Evan - regular feed times, nap times and bed time in the evening. But just lately he&apos;s really started to fuss in the evenings. I think he&apos;s got to that age where he really knows that if he screams his head off Emma comes running and I think he&apos;s playing us good!  
        ///
        ///At the end of last week we took him round to Emma&apos;s mums and we made the mistake of trying him out in the travel cot - boy did he throw a paddy! After that I dec [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w26Two {
            get {
                return ResourceManager.GetString("y1w26Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evan has the most adorable fluffy blonde hair and one day this week I just had the urge to put some hair wax in his hair. I tried to hide this from Caroline but she noticed as soon as I walked into the room :). &quot;What have you put in his hair you naughty Mummy!&quot; she said... He did look really cute with his hair doing a trendy scruffy look.  
        ///
        ///Evan is developing really well and his routine is really starting to go smoothly. He&apos;s on 3 meals a day and now only has breast feeds throughout the night when he wak [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w27One {
            get {
                return ResourceManager.GetString("y1w27One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This week Evan decided to throw his dinner at his mummy! I haven&apos;t bought a high chair, though we&apos;ll be going to the shops soon because Evan is outgrowing all the other chairs that we use for feeding. We&apos;ve started feeding him in his bouncer and beside the fact that he has now figured out how to bounce himself, there is also no plastic tray and he can lean forward towards me. He caught me by surprise one afternoon and this time flicked the spoon out of my hand missing him, the chair, the floor but hitting m [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w28One {
            get {
                return ResourceManager.GetString("y1w28One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This was a weird week and one I found hard to cope with. Not having Caroline around was horrible and Evan and I missed her dearly. My family and friends were brilliant this week helping with Evan so that I could sit vigil beside Caroline&apos;s bed in hospital. She was moved into intensive care this week and it meant that no children were allowed at all, so I couldn&apos;t even take Evan in with me if I was stuck for a baby sitter. I felt terrible leaving Evan for hours on end but I needed to be with Caroline for whe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w29One {
            get {
                return ResourceManager.GetString("y1w29One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I think I can confidently say that I have just experienced the worst week of my entire life. As Emma mentioned, I had to go into hospital, for my own benefit I&apos;ve started writing a hospital diary which can be seen [here](../../../../hospital/day/1) if interested.  
        ///
        ///I must admit that I&apos;ve been probably less than helpful with Evan so far over the past six months. I&apos;ve thrown myself into my University work and pretty much let Emma do all the _mum_ stuff. A few feeds and changes has been about the basis of m [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w29Two {
            get {
                return ResourceManager.GetString("y1w29Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After the crazy hectic first week at home, most people we knew had managed to see Evan and the daily visits had died down. I had been warned in pregnancy to expect my washing machine to be busy and I am starting to see that now. On average we are doing 2 loads a day when before having Evan I&apos;d only have the washing machine on 3 times a week! I just hope my washing machine survives the extra workload as even before Evan I noticed it was starting to groan lots.  
        ///
        ///The long hard nights started this week and  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w2One {
            get {
                return ResourceManager.GetString("y1w2One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m not exactly sure if week two was better or worse than the first week. It was nice that the visiting died down a bit and we were able to get used to a new life of three, but it was also hard dealing with Evans ever-increasing crying.  
        ///
        ///It doesn&apos;t matter how many books you read, or what advice people give you, every baby is different. I kept reading how babies need to be calmed when they are crying by gentle rocking and speaking softly buy none of that worked with Evan. Quite the opposite in fact. I fo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w2Two {
            get {
                return ResourceManager.GetString("y1w2Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evan&apos;s highchair arrived this week and we started feeding him in that, safely strapped in and no chance of bouncing around and making himself sick :). He really liked it though and he loves it when the cats hang around at our feet thinking it&apos;s feeding time for them also.  
        ///
        ///We had a projectile puking incident this week! I&apos;d just finished giving Evan his bottle and he must have had some trapped air or something like that because the moment I sat him upright on my knee to be winded, he just brought up a co [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w30One {
            get {
                return ResourceManager.GetString("y1w30One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This has been a strange week for me as it was my first week at home out of hospital. As I have been so incapacitated Emma has had to do everything with Evan and around the house - I can&apos;t even do nappy changes as leaning forward hurts too much. I missed Evan in hospital and he changed quite a lot in those two weeks but because I can barely interact with him even now I feel a bit disconnected. Aside from the physical pain, I have also felt drained of energy and haven&apos;t had the energy to pull silly faces at h [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w30Two {
            get {
                return ResourceManager.GetString("y1w30Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I did my last morning boob feed last Wednesday (20th July) and I am really starting to notice them drying up. I am expecting it to take roughly 2 weeks. At the moment it is very strange and uncomfortable at times. The boob that had the last feed is coping a lot better than the one that was not relieved... As the ducts dry up, it makes your boob look really weird instead of having engorgement all over, you tend to find that just parts of the boob are engorged. Evan seems to really like to grab at my boobs so [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w31One {
            get {
                return ResourceManager.GetString("y1w31One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This was another stressful, hectic week. We had our anniversary and enjoyed a lovely meal at a Chinese restaurant in the Village near to where my mum lives so that she could baby sit for us. It was a successful evening and Evan slept ok in his travel cot.  
        ///
        ///Our week then deviated from normality. Caroline attended a nurses appointment for a scheduled dressing change on her surgery wound only to find out that she needed to return to hospital for some antibiotics as the wound had become infected. It was not [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w32One {
            get {
                return ResourceManager.GetString("y1w32One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evan had an afternoon at his friend Alex&apos;s house this week. He also had the pleasure of spending time with Megan as she had travelled all the way from Bath to visit family and friends. It&apos;s lovely to see babies playing together and they absolutely adore other babies. Megan and Alex are both crawling and Evan was quite content with his little bum shuffle, and didn&apos;t mind it when Alex crawled all over him - it actually made him giggle! I think Evan will do fine at nursery when he starts next month, though he  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w33One {
            get {
                return ResourceManager.GetString("y1w33One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caroline came home from hospital at the start of this week and hopefully that&apos;s the end of this nightmare. Whilst in hospital Caroline was able to rest and her surgical wounds are now looking so much better. Caroline had bought some special cream that you can rub into scars that will hopefully soften them and make them fade. She bought from the US and so to make the shipping a one off, she bought 5 tubes of it, unfortunately for her she has shown an allergic reaction to the cream. Waste not want not - I&apos;ve  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w34One {
            get {
                return ResourceManager.GetString("y1w34One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I think Evan has lost that natural swimming reflex that he had when he was younger and we unfortunately haven&apos;t been able to take him swimming as much as we had liked over the summer period. When we first took him swimming a few months ago, if you went into the water with him lying on your hand belly down, he would flap his arms and legs in this swimming reflex. He doesn&apos;t do this anymore when we take him. He was a little subdued this week in the swimming pool and just wanted to cuddle me and grab the lane  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w35One {
            get {
                return ResourceManager.GetString("y1w35One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This week Caroline made Evan a fish pie and we are no longer using the little ice cube sized potions for main meals as he would be having about 3 or 4 of them by now. Instead we are using much bigger single containers and I probably think that these are a little too much for Evan at the moment but I&apos;m sure it won&apos;t be for long. All it means is that we have some leftovers because he gets bored *(though he always has room for some pudding!)* He enjoyed the fish pie and it was very fishy indeed with quite a st [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w36One {
            get {
                return ResourceManager.GetString("y1w36One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have a tooth! I noticed Evan&apos;s gum looked a lot paler this week and realised that it was the tooth coming up through the gums. He&apos;s had his grumpy moments this week - more so than I have experienced so far and he&apos;s also had a couple of days when he didn&apos;t want much dinner or evening bottle. I figured that this was finally the teething that we&apos;d thought we were experiencing all those months ago. It&apos;s quite funny actually, as we have been putting dentinox on Evan&apos;s gums on and off since he was 3 months. I&apos; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w37One {
            get {
                return ResourceManager.GetString("y1w37One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This is my penultimate week at home with Evan so I decided to get Evan weighed as I don&apos;t know when I&apos;ll next be able to do it. He is definitely big enough for his new car seat now as he weighed in at 20lb 4oz, which is a few grams over the 9 kilo requirement.  
        ///
        ///We took Evan swimming again this week and at first we thought it would be a nightmare as the water was much colder than it had been on previous visits and Evan&apos;s teeth started to chatter at first. He was ever so excitable though and he got some g [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w38One {
            get {
                return ResourceManager.GetString("y1w38One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Well this is it... The time has come for me to return to work. Unfortunately as much as I love spending time with Evan and being his full time carer, I have to pay the bills and if I am to ensure that Evan has lots of great things, I need to earn some money. I think nursery will be good for Evan because he loves the social aspect and playing with different toys that he doesn&apos;t have at home and seeing other babies. I think he would have become bored at home with me as I certainly wouldn&apos;t be able to do the k [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w39One {
            get {
                return ResourceManager.GetString("y1w39One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After the recent evening events with Evan and his sleeping problems we decided it was probably best if Caroline moved downstairs to sleep on the futon. I was not very receptive to this suggestion but I do understand how much Caroline needs her sleep for University as she struggles to stay awake in lectures anyway!  
        ///
        ///We had our first visit from the health visitor this week as we were no longer being cared for by the midwives. Evan certainly doesn&apos;t have a problem eating and breast feeding is going smoothl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w3One {
            get {
                return ResourceManager.GetString("y1w3One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monday of this week was the end of my Christmas holiday and time for me to go back to Uni. Emma wasn&apos;t looking forward to it at all but thankfully my timetable is fairly light and as long as I&apos;m able to study at home I don&apos;t have to be there all that much. One thing that did worry me though was the sleep I was getting. At night times it was taking 1-2 hours to get Evan off to sleep then I found that I kept waking up with his little kicks and fidgets. Then of course he&apos;d wake up screaming several times a nig [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w3Two {
            get {
                return ResourceManager.GetString("y1w3Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When I started preparing myself for the inevitable return to work, nothing I thought up actually came close to comparing to the real deal! I was hoping that I would be kept really busy to keep my mind off of Evan. My work did ok on that part except for not having my own PC for my first day back, I&apos;ll forgive them for that as they gave me a brand new shiny lush PC the very next day. I did think a lot about Evan and I think I only telephoned them once in his first week so that&apos;s not bad.  
        ///
        ///Going on our exp [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w40One {
            get {
                return ResourceManager.GetString("y1w40One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If someone had told me beforehand about the events that would happen this week I probably would have laughed. I had just completed my first week back at work after 10 months off and when I go into Evan on Sunday morning this week, his eye is oozing with puss. I tried to keep the eye clean but within minutes of wiping it, the infectious gunk had returned. I was sure Evan needed to see a Doctor so I sent a mobile text to warn my boss that I wouldn&apos;t be in on Monday. Little did I realise that this would actual [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w41One {
            get {
                return ResourceManager.GetString("y1w41One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evan and I actually settled back into our work routine fairly quickly this time round. I was certain that we would have problems reintroducing Evan to nursery as Evan was only there for one week before being off sick for a week with me. I am glad that this was not the case though. He seemed fine and actually started sleeping a bit better in the day time at nursery this week.  
        ///
        ///My mum was released from hospital this week, but not even 24 hours later when she had a visit from her GP, they decided to send h [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w42One {
            get {
                return ResourceManager.GetString("y1w42One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evan absolutely adores the cats and he just won&apos;t leave them alone now. If he is on the floor and they come into view, he&apos;s off, following them around laughing and being generally noisy. He doesn&apos;t mean to scare them, he just wants to be able to touch them. The problem is, he is quite heavy handed and also very loud and excitable around them that it just scares them. If we are there to help him stroke them, it&apos;s ok, but most of the time he just follows them as they are just that little too quick for him. He [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w43One {
            get {
                return ResourceManager.GetString("y1w43One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This was my 5th week back at work and it was another chaotic one. Evan already had a cough and I just put it down to the start of Autumn and that it was just something minor. By the time Sunday came though, Evan was sleeping lots and not as playful as usual. Throughout the night Evan&apos;s coughing became worse that it actually woke the whole house up several times and I was having to get up to calm him every 45 minutes or so. This prompted Caroline to move her bed downstairs. Evan and I still made it into nurs [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w44One {
            get {
                return ResourceManager.GetString("y1w44One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evan is fully recovered from his bronchitis and he also regained his big appetite this week. Caroline and I still have the remnants of our colds but I am just glad that Evan is ok.  
        ///
        ///Evan can really object to things when he wants to. We think he&apos;ll be a &quot;foot stamper&quot; for sure when he has tantrums when he is older. He already swings his arms and bounces on his legs! Sometimes the only thing I can do to get his attention is to give him something new as a distraction. Handing him a toy does nothing apart f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w45One {
            get {
                return ResourceManager.GetString("y1w45One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve had some major achievements this week with Evan. He can now stand on his own without holding on for long periods of time. This has happened ever so quickly, at first it was just a second or two before flopping to the floor. By the end of the week he was able to stand for 22 seconds!  
        ///
        ///I think sometimes he doesn&apos;t realise he is doing it. He&apos;ll be holding onto the table or me playing with a toy. He will then grasp the toy with both hands, standing alone. He then has this startled look as he suddenly  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w46One {
            get {
                return ResourceManager.GetString("y1w46One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As the sayings go *&quot;You wait hours for a bus and then 3 come along at once&quot;*, or *&quot;bad things always happen in three&apos;s&quot;*. Well, this week we had our third illness with Evan. I had noticed towards the end of last week that he was pooing a lot more than usual and it was getting rather smelly. Over the weekend it peaked and Evan did about 6 poos in one day. I took him to nursery on the Monday and told them I was worried and that I would be contacting a Doctor that day. By the time I collected him, his poor lit [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w47One {
            get {
                return ResourceManager.GetString("y1w47One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We had one funny incident with Evan this week. We were out doing our weekly shop and the lady at the McDonalds inside Asda gave us this balloon tied onto a plastic stick for Evan to play with. I thought it would be ok under supervision so I let him play with it and he happily banged it around all over the place, giggling when he inadvertently bonked it against either my head or his own.  
        ///
        ///The balloon was still in the house one evening when we arrived home and we were playing with it again in front of Eva [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w48One {
            get {
                return ResourceManager.GetString("y1w48One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I was playing with Evan this week after his evening bath and he escaped my grasp as I was drying him. I just let him sit a few feet away bouncing happily on his feet as he knelt down. I was playing with his little bath cups and I started gently tossing them into the air so that they fell all over the floor and he was beside himself, in extreme giggles. I started to laugh because he was. He was laughing so much I could see his eyes watering. I carried on playing with the cups when suddenly I smelt it. No way [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w49One {
            get {
                return ResourceManager.GetString("y1w49One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I conquered one of my fears this week! I went to the mother and baby group to get Evan weighed and I also stayed for the session, which happened to be on sleep and routine! Routine?!? - Evan doesn&apos;t have one, so that&apos;s the next task to try and introduce, initially by going to bed at the same time every night and doing the same things to get him prepared for sleep time. Evan weighed in at 10lb 1oz and little chubby chops is starting to grow out of his vests. A pile of clothes that he is too big for has been  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w4One {
            get {
                return ResourceManager.GetString("y1w4One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to At last I&apos;m starting to notice some real changes in Evan&apos;s behaviour now. In the beginning he was extremely insecure, we often had no clue why he would be crying and have a very hard time settling him. He was not very responsive at all. I have a couple of books about baby development and I read a little each week. Of course every baby is different but it was a little frustrating when he didn&apos;t seem to be exhibiting any of the behaviours I was reading about.  
        ///
        ///But this past week we&apos;ve had more success. We [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w4Two {
            get {
                return ResourceManager.GetString("y1w4Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have a new member of the family and Evan absolutely adores him. His name is Noodle and he&apos;s Caroline&apos;s early Christmas present. He&apos;s really little and Evan *(although harmless)* scares him because his movements are so loud and jerky.  
        ///
        ///I had a half day this week to attend Evan&apos;s nativity play. Evan was forming part of the rainbow and his colour was yellow. I had to provide yellow clothes for him to wear, I couldn&apos;t find yellow trousers so in the end he wore cream trousers and a yellow t-shirt. They al [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w50One {
            get {
                return ResourceManager.GetString("y1w50One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We popped over to our next door neighbour this week to deliver our Christmas card and we decided to give her a bottle of wine as a thank you for all the help we have had from her. We decided to stay for a glass of wine to catch up and she was very fortunate to witness a first time event from Evan. He&apos;s certainly not shy in new places and was crawling and playing all over her lounge floor being a little cutie as usual.  
        ///
        ///Evan stood up and suddenly started to walk around in a circle whilst we all clapped a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w51One {
            get {
                return ResourceManager.GetString("y1w51One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This was Evan&apos;s last week in his first year and it&apos;s amazing how quickly time flies by when watching your baby grow into a little boy. This final week started with a birthday party for Alex - one of Evan&apos;s baby buddies. We managed to get most of the gang together for one final meet before Christmas and it was lovely. All the babies are walking now, though Evan is still very wobbly and he would still prefer to crawl at times where as the others are very much mobile and walking very steadily. His first steps  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w52One {
            get {
                return ResourceManager.GetString("y1w52One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evan must have had a growth spurt recently, he put on 10 ounces this week when I weighed him at the Mother and Baby group. He weighs 10lb 11oz now and we started having issues with the nappies leaking so we decided to move him into the big boy nappies. We probably should have moved him up to the next size earlier to save us wasting nappies but I wasn&apos;t aware that the weights overlapped and I was trying to wait until Evan was 11lbs before moving onto the next!  
        ///
        ///The swing that my mum bought for us last we [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w5One {
            get {
                return ResourceManager.GetString("y1w5One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On Tuesday Emma had an appointment at the Dentist so I had Evan on my own. This was only the second time since his birth that Emma had been away from him for any length of time. Of course, he grizzled lots! I decided to take him for our usual walk as that has always settled him but this time it was not to be. He was really screaming and in my flap I just forgot everything - his hat, a muslin, mitts! So he was probably cold. To my embarrassment he just screamed all the way around the housing estate! He did f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w5Two {
            get {
                return ResourceManager.GetString("y1w5Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I have finally started to feel much better now, the mother of all periods has gone and everything appears to have healed. My mum took me for my hospital scan this week and Evan had his first ride in a lift, he pulled his funny little face that he does when he&apos;s about to have a whiney cry and I was thinking oh god not in here. My mum just looked at him and said something like *&quot;You can stop that right now!&quot;* and to my surprise he did. Do you think I have that effect on him?!?!  
        ///
        ///That day Evan got to visit [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w6One {
            get {
                return ResourceManager.GetString("y1w6One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emma has been exclusively breast-feeding Evan since birth but sometimes she needs to go out somewhere where she can&apos;t take him along. When that happens she has to try to get him fed before she goes and get back quick as he&apos;s still feeding pretty much every two hours!  
        ///
        ///So this week she thought she&apos;d try expressing so we could try a bottle feed. I&apos;ll let Emma go into details about the expressing :-) Well a couple of days later we had a couple of ounces of milk **(!)** and we tried it out - he seemed to lo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w6Two {
            get {
                return ResourceManager.GetString("y1w6Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My little boy is growing so much, he has outgrown most of his baby clothes and me being a naughty mummy have spent all of his toys and clothes monthly allowance for the next 2 months already and it wasn&apos;t on the clothes we needed! He is looking so much older and definitely doesn&apos;t look like a new born anymore. He weighed 11lb 12oz this week which is a great weight so even though at times I feel like my boobs are drained and not satisfying him, he is certainly gaining the weight that he needs.  
        ///
        ///This week [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w7One {
            get {
                return ResourceManager.GetString("y1w7One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The things we do to placate our babies... One morning in the week Emma had had a rough night and was really tired so I took Evan in the front carrier so she could get some undisturbed sleep. We were milling around the house quite happily and I got peckish so I went to get myself some cereal and went back upstairs to do some stuff at the computer. Evan had other ideas :/ He started to cry so I stood up and jigged him a bit. It still didn&apos;t work so I turned on Avril Lavigne and jigged a bit more. In the meant [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w7Two {
            get {
                return ResourceManager.GetString("y1w7Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have found a formula milk that Evan will drink *(we hope it wasn&apos;t a one off)* and he quite easily drank 8oz. It&apos;s nice for Caroline to have some bonding time with Evan and it really is lovely watching him feed with those gorgeous little eyes looking up at you. I don&apos;t always have expressed breast milk at hand and sometimes I feel like my boobs have nothing in them so having formula available will be very handy. It&apos;s especially useful for when we go to visit friends because it can be terribly lonely havi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w8One {
            get {
                return ResourceManager.GetString("y1w8One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Have you ever noticed how much conflicting advice is banded around about babies? And the more you read and the more people you talk to the more confusion there is. Evan is almost 2 months old now and he still can&apos;t get himself to sleep. 9 times out of 10 the only way we&apos;ll get him asleep is to let him fall asleep after a feed, on our chests, or in our arms to music. If he&apos;s fast asleep then we can put him down to bed and sometimes he&apos;ll stay asleep for a while - but usually he wakes within a few minutes. Wh [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w8Two {
            get {
                return ResourceManager.GetString("y1w8Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This week was probably one of my worst weeks so far. We were due for our checks with our GP and if Evan was all healthy he&apos;d also have his first dose of injections.  
        ///
        ///We had both been given the all clear from the GP and Evan had his routine injections. The nurse was very nice and had prepared both injections beforehand to give to Evan as quickly as she could to make it less traumatic for us both. It was horrible having to watch, he was a very brave boy and it wasn&apos;t until the first injection was almost f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w9One {
            get {
                return ResourceManager.GetString("y1w9One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s been quite a week this week. On Tuesday Evan had to go get some jabs done and usually I would go along with them but I had to stay in and wait for a delivery. I heard all about it when they got back and mummy and baby were both rather traumatised.  
        ///
        ///To make matters worse it was on this day that Emma realised that Evan was actually constipated! Because I am at Uni a lot I don&apos;t change him all that much so I didn&apos;t really notice that he&apos;d not done a poo in a while. Sometimes Emma can be a little overl [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w9Two {
            get {
                return ResourceManager.GetString("y1w9Two", resourceCulture);
            }
        }
    }
}
