//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvansDiary.Web.Diary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Year2008 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Year2008() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvansDiary.Web.Diary.Resources.Year2008", typeof(Year2008).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string y4Feb {
            get {
                return ResourceManager.GetString("y4Feb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to a brand new year! A new start for many of you, one that Evan and I are part of. The viewings for the sale of the house were not going well and with the market taking a downturn I made a decision in January to buy Caroline&apos;s half of the house meaning that I can now take my time to decorate the house and move in my own time when the markets are more lively.  
        ///
        ///I was having a hard time finding a house that was a similar size, for the same price. It was obvious to me that I&apos;d be downgrading if I we [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y4Jan_1st {
            get {
                return ResourceManager.GetString("y4Jan_1st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A night to remember! Evan went to stay with Grandma for a few days this week to allow me to travel to London with friends to watch my beloved Tottenham Hotspur face their arch rivals Arsenal in the Carling Cup Semi-final at White Hart Lane.  
        ///
        ///We left work at 4.30pm and drove into London, it took us roughly 2 and a half hours to get there but it was worth every minute.  
        ///
        ///I was feeling optimistic, Tottenham should have been 1 up from the first leg at Arsenal 2 weeks earlier and I just had a feeling that [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y4Jan_22nd {
            get {
                return ResourceManager.GetString("y4Jan_22nd", resourceCulture);
            }
        }
    }
}
