//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvansDiary.Web.Diary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Year2007 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Year2007() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvansDiary.Web.Diary.Resources.Year2007", typeof(Year2007).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We had an interesting start to this month when we visited Caroline&apos;s mum for the Easter weekend. She&apos;d been planning a little visit to a public garden that has lots of flowers and special gardens for the public to come and see. I hadn&apos;t really thought too much about it until the actual day. Usually when we go out with Evan, there is two of us on hand to deal with him as he does have a tendency to wander and get upto general mischief. Today was going to be slighty different as Caroline&apos;s mum now requires a w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y3Apr {
            get {
                return ResourceManager.GetString("y3Apr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string y3Dec {
            get {
                return ResourceManager.GetString("y3Dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;ve been a bit repetitive of late when it comes to the music that I&apos;ve been listening to in the car when there is nothing interesting to listen to on the radio. I&apos;ve especially enjoyed listening to a mix CD that I compiled with some Snow Patrol, The Feeling and The Kooks - oh and some retro song that I heard on the radio (Ain&apos;t Nobody by Rufus &amp; Chaka Khan). Evan seems to enjoy it to as he always bops his legs and gets his Piglet teddy bear dancing in the car when the songs are playing. This month however  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y3Feb {
            get {
                return ResourceManager.GetString("y3Feb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We all went to the dentist this month for our 6 month check up. Last time Evan didn&apos;t have as many teeth so a simple smile and giggle was enough to let the dentist check them. This time around he&apos;s got all of his child teeth except for the final set of molars. I&apos;d been practicing with Evan for the week before opening our mouths and saying *&quot;Aaaah&quot;*. I thought we had it sussed but when we attempted to do it for the dentist Evan became shy and refused.  
        ///
        ///Caroline went in first, while I amused Evan in the w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y3Jan {
            get {
                return ResourceManager.GetString("y3Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evan has shown signs of really picking up on things that we do around him lately. A few months ago we were watching my ladies football team play their final home game of the season. I had to take Evan with me because Caroline was away at a Karate event. We took his ball and played football on the pitch when it wasn&apos;t in use - he absolutely loved that. Every time I cheered for the team, Evan shouted *&quot;Come on Tottenham&quot;* making everyone in the stand laugh at how cute he was. We were all cheering for Burnham, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y3Jul_10th {
            get {
                return ResourceManager.GetString("y3Jul_10th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My First Festival - Aged 2. How many of us can say that? Evan has just been to his first festival *&quot;Legoland Live&quot;.* We&apos;ve had these annual passes for Legoland, so we thought we&apos;d try and make a note of some events that would be good to go to throughout the summer. Today was a special festival with all the favourite stars of children&apos;s TV *(Barney, Lazy Town, Pingu, Bob the Builder and lots more).*  
        ///
        ///Because of the annual passes, we didn&apos;t feel the need to go early and get our money&apos;s worth because our e [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y3Jul_14th {
            get {
                return ResourceManager.GetString("y3Jul_14th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Happy Birthday to me.... or Happy Birthday to Evan?  
        ///
        ///Today was my 28th birthday - wow I&apos;m getting old, so close to the big 30! It was a Monday and we weren&apos;t doing anything special so I went to work as usual, stopping off at my local Krispy Kreme doughnut shop to collect 4 dozen doughnuts for the guys at work. I saved 3 doughnuts to take home as I knew we hadn&apos;t arranged a birthday cake so I planned to put some candles on my doughnuts and have a makeshift birthday cake.  
        ///
        ///I wasn&apos;t sure if Evan would  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y3Jul_30th {
            get {
                return ResourceManager.GetString("y3Jul_30th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evan had a birthday party to go to today as a friend from nursery was having her 3rd birthday. I wasn&apos;t particularly prepared for this as we&apos;d only just come back from our holiday in France. Nevertheless, I still managed to get a present and card during my lunch break in the week leading up to the date. I wasn&apos;t sure what to expect, but I figured it would be something like the birthday party that he went to at Christmas time.  
        ///
        ///Evan had a nice sleep in the car on the way to the party so I hoped he&apos;d last [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y3Jul_7th {
            get {
                return ResourceManager.GetString("y3Jul_7th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We finally made the trip to a Zoo as this is one place I wanted to go to last year but we never quite made it. Evan absolutely loved it, although I was disappointed that he didn&apos;t get to see his favourite animal &quot;the Elephant&quot; because Marwell Zoo doesn&apos;t have them. Next time, we&apos;ll take him to Colchester Zoo as I believe they have Elephants there. We didn&apos;t arrive until after lunch time, but we still managed to squeeze the whole Zoo in. The weather was fantastic, possibly a little too hot as the poor animal [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y3Jun_10th {
            get {
                return ResourceManager.GetString("y3Jun_10th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to __*&quot;Bienvenue à l&apos;édition en Français!&quot;*__  
        ///
        ///Well - not quite! The month sort of started with a French event and ended with one. My speech is somewhat better but I can&apos;t really write it. We were invited to a BBQ at Caroline&apos;s brother&apos;s house at the end of May. This BBQ was special as her relatives from France had travelled down for a long weekend and this would be the first time that I met them. It was a really lovely day despite the terrible weather that we had and I just wish I could have chatted with  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y3Jun_1st {
            get {
                return ResourceManager.GetString("y3Jun_1st", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mr brother and his fiancé Pascale got married at the end of June. We did try to get Evan there in one piece, it all went pear shaped when I arrived to collect him from nursery the night before only to see that he was now sporting a nice black eye. Evan had decided it would be a good idea to dive on some pillows earlier in the day, the only issue being he missed them.  
        ///
        ///The wedding happened to be on the day before we flew to France for our small break. We left it a little late to leave because we wanted t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y3Jun_22nd {
            get {
                return ResourceManager.GetString("y3Jun_22nd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The trip to France was our first holiday in 7 years and our first holiday with Evan. No more relaxing in the sun holidays for us! Evan was so excited about the aeroplane, though Caroline did wonder how he&apos;d react when he saw that they were bigger *(much bigger)* than the toy ones that he is used to playing with. We arrived at the airport with a fair amount of time to spare and were informed the flight was delayed. Evan had a real issue with the baggage as he didn&apos;t like his toys disappearing down the convey [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y3Jun_29th {
            get {
                return ResourceManager.GetString("y3Jun_29th", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Now that Spring has finally settled we&apos;ve started compiling a list of places that we&apos;d like to take Evan to this year. We&apos;re hoping to do something with Evan every weekend so that he doesn&apos;t get bored, whether it&apos;s going to see family and friends, visiting a local attraction like the indoor play area or going out of our way to visit something completely new. I&apos;m looking forward to Marwell Zoo as it&apos;s been so long since I&apos;ve been to a Zoo and I&apos;m looking forward to seeing the Giraffes and Elephants *(Hopeful [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y3Mar {
            get {
                return ResourceManager.GetString("y3Mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to May has been the month of first times. Caroline went to Wales with her Karate club for a week of intensive training. I was really looking forward to this as it meant I was going to have to do everything by myself. We&apos;re a really good team and you only realise how much each other does when you&apos;re left alone to do it all. She went on the Bank Holiday weekend so Evan and I were left to our devices on the Bank Holiday Monday :). I spent a few hours cooking all the food required for the weeks lunches and the eve [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y3May {
            get {
                return ResourceManager.GetString("y3May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string y3Nov {
            get {
                return ResourceManager.GetString("y3Nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string y3Oct {
            get {
                return ResourceManager.GetString("y3Oct", resourceCulture);
            }
        }
    }
}
