//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvansDiary.Web.Diary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Year2005 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Year2005() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvansDiary.Web.Diary.Resources.Year2005", typeof(Year2005).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My experience of the birth is totally different to that of Caroline&apos;s. When I think back, parts of it are now starting to blur and I need reminding from those that were present to relive certain events. I guess the pain relief through drugs and that of my natural pain relief are part of the reasons for me not remembering it. I personally handled being pregnant and going through the labour better than I would have handled being the partner who felt completely helpless at times.
        ///    
        ///For two days I was havi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w0One {
            get {
                return ResourceManager.GetString("y1w0One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watching your loved one go through the pain of labour when there is virtually nothing you can do to alleviate her pain is heart-wrenching. As the labour drags on and on sapping every ounce of her energy and Christmas Day fades into Boxing day it&apos;s hard to imagine that this little baby will ever actually be born...  
        ///    
        ///The first signs of labour started early on the morning of Christmas Eve. Emma&apos;s waters appeared to break so she phoned the hospital and they advised her to come in due to risk of infectio [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w0Two {
            get {
                return ResourceManager.GetString("y1w0Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to My recollection of days and times became completely muddled after the birth of Evan. I was wheeled up to the postnatal ward at 7am in the morning and because we then went to bed it actually feels like I was in hospital for a day longer than I actually was. I didn&apos;t get much sleep at all and 2 hours later I woke up feeling terrible. My right leg was still completely dead and I couldn&apos;t move at all. When Evan started to cry I couldn&apos;t tend to him because of my problems with the epidural and I didn&apos;t have a nu [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w1One {
            get {
                return ResourceManager.GetString("y1w1One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emma and Evan were taken up to the postnatal ward at about 7am and we were all thoroughly exhausted. Her mum and I waited until they were both settled and then went home for some well-earned sleep! The drive home was weird. It was about -3 outside and the car was frozen solid. To me it was the end of a very long night but in reality the day was just starting. As I started to drive the emotion of it all really hit me and I had tears streaming down my face all the way home. I slumped into bed and managed to g [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w1Two {
            get {
                return ResourceManager.GetString("y1w1Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to After the crazy hectic first week at home, most people we knew had managed to see Evan and the daily visits had died down. I had been warned in pregnancy to expect my washing machine to be busy and I am starting to see that now. On average we are doing 2 loads a day when before having Evan I&apos;d only have the washing machine on 3 times a week! I just hope my washing machine survives the extra workload as even before Evan I noticed it was starting to groan lots.  
        ///
        ///The long hard nights started this week and  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w2One {
            get {
                return ResourceManager.GetString("y1w2One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I&apos;m not exactly sure if week two was better or worse than the first week. It was nice that the visiting died down a bit and we were able to get used to a new life of three, but it was also hard dealing with Evans ever-increasing crying.  
        ///
        ///It doesn&apos;t matter how many books you read, or what advice people give you, every baby is different. I kept reading how babies need to be calmed when they are crying by gentle rocking and speaking softly buy none of that worked with Evan. Quite the opposite in fact. I fo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string y1w2Two {
            get {
                return ResourceManager.GetString("y1w2Two", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      
        ///    .
        /// </summary>
        public static string y1w3One {
            get {
                return ResourceManager.GetString("y1w3One", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///      
        ///    .
        /// </summary>
        public static string y1w3Two {
            get {
                return ResourceManager.GetString("y1w3Two", resourceCulture);
            }
        }
    }
}
