//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EvansDiary.Web.Diary.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Year2006 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Year2006() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EvansDiary.Web.Diary.Resources.Year2006", typeof(Year2006).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As the weather has now started to improve and Evan is &quot;Mr Confident&quot; on his feet we&apos;ve started to take Evan outdoors much more this month. We decided our first outdoor trip would be a fairly close one and it would last only the morning. I&apos;d already highlighted a few places that I wanted to visit this year with Evan so we chose [Odds Farm Park](http://www.oddsfarm.co.uk/). It&apos;s baby season in the animal kingdom and at Odds Farm they had lots of baby lambs, piglets and goats, some literally hours old for Evan [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y2Apr {
            get {
                return ResourceManager.GetString("y2Apr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All those nice things I was saying about Evan and nursery last month completely changed this month. We&apos;d lost a few of the nursery staff in Evan&apos;s room in July, some that I was rather fond of and Evan absolutely adored. He seems to have his favourites! This month I received a shock when our favourite member of staff, the lady in charge of Evan&apos;s room decided that she too wanted to leave and it was all rather sudden. There has been a lot of changes implemented in the nursery since the change in management an [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y2Aug {
            get {
                return ResourceManager.GetString("y2Aug", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s birthday time! This year has flown by and Evan has grown up so much. He&apos;s now this little boy who chats - a lot! :)  
        ///
        ///We popped round to our neighbours to deliver Christmas cards and presents one weekend this month and Evan had so much fun playing with their daughter, who is about 9 months younger than Evan. Watching them together is so much fun, she just hangs on to him and uses him to climb up onto her feet and he just seems to tower over her. He was so excited that he just kept rushing around whe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y2Dec {
            get {
                return ResourceManager.GetString("y2Dec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It doesn&apos;t feel like only a year ago I was a new mum doing the whole mother and baby thing going to my weekly weigh-in clinics to make sure that Evan was getting enough breast milk and developing as he should. Time really has flown by; sometimes I really miss it. This month has been a stressful month and it has taken its toll on all of us. Some days I just wish it wasn&apos;t such a rush and that Evan and I could once again just spend some quality time together. It doesn&apos;t seem right that Saturday and Sunday are [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y2Feb {
            get {
                return ResourceManager.GetString("y2Feb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This month saw the change over to Evan nearly always walking and not so much of the crawling anymore. By the end of his first week back at nursery there was no stopping him.   
        ///
        ///As a result of his increased walking, especially as he is still unsteady some of the time, we are seeing more bumps and bruises than ever before. He is ever so confident and will quite happily eat bits of food off of your plate and then walk around the room chomping away. He&apos;ll even twist and turn a lot especially when holding a t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y2Jan {
            get {
                return ResourceManager.GetString("y2Jan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evan spent his first night away from home this month. It was Caroline&apos;s graduation ceremony and we had a very early start so to save my mum having to get up at 5am to come over to baby sit Evan, we decided it would be better for all parties if he stayed the night at hers. It was a real success and something we hope to do again because it was great for Grandma to spend time with Evan and he just loved the mini adventure! I missed him, as expected but that was only because I&apos;ve never spent any overnight time  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y2Jul {
            get {
                return ResourceManager.GetString("y2Jul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve seen a lot of changes this month most notably with Evan&apos;s feeding routine. I couldn&apos;t understand why Evan was eating so well at nursery but when he&apos;s at home he just refuses. It suddenly occurred to me that it could be the way that we were initiating the feeding. At nursery Evan sits around a table with up to 7 other children and the nursery ladies just sit at a corner to help when necessary. They are all sitting in little versions of grown up chairs and they are left to feed themselves and they do ju [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y2Jun {
            get {
                return ResourceManager.GetString("y2Jun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We&apos;ve converted Evan&apos;s walker into his car now and he loves to ride on it. He loves it when mummy pushes him really fast steering him around the room. He can however drive himself somewhat more slowly using his feet correctly. He still has to master the steering though and he has no problems getting on and off it either. He has also mastered turning his walker full of bricks instead of crying when it hits the wall. He now anticipates the distance to the wall and turns it accordingly, most of the time he doe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y2Mar {
            get {
                return ResourceManager.GetString("y2Mar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evan recently started showing signs of noticing things outside in particular he points to birds and makes *&quot;oohh&quot;* noises when they fly around and hop along the floor. This month showed a new interest for Evan, that of planes. He absolutely adores them and seeing as we live just off the flight path to Heathrow Airport we do get our fair share or aeroplanes flying above the house and some are usually a lot closer if they are coming in to land, as Heathrow is only about 20 minutes away from where we live. He  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y2May {
            get {
                return ResourceManager.GetString("y2May", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s been a funny old month this month. I&apos;ve been so busy, yet I don&apos;t really have much to show for it. Evan and I had some time off unexpectedly this month due to him being a little bit poorly. Normally when he&apos;s not allowed to go to nursery it&apos;s not because he is really ill, but it&apos;s just to protect the other children and he&apos;ll spend most of the time at home running around playing. This time though, it was obvious that he was in discomfort, he wanted lots of cuddles and attention. I did manage to find som [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y2Nov {
            get {
                return ResourceManager.GetString("y2Nov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The cold nights have really crept up on us this month. Evan was still wearing his summer jacket in the day but I suddenly realised the need for a proper winter coat when I took Evan to watch a local football match one evening early this month. Caroline was out for the evening, so Evan had to come with me. I packed up a bottle of milk for him, hat, jacket and gloves and he even had 3 layers on under the jacket. I just couldn&apos;t keep him warm at all, where he had been drinking his milk, the fluid dripped on hi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y2Oct {
            get {
                return ResourceManager.GetString("y2Oct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Evan and I went to see my mum this month and we stayed overnight so that Evan could see more of his grandma. We had an exhausting but very enjoyable time, my mum would probably echo those thoughts as well. As it happens, she also had a friend visiting from Cornwall but as she was also splitting her time with others, she wasn&apos;t at my mums on the days we went. We met at Ikea in Lakeside as that was half way between the location where my mums friend was going to and we fancied a shopping trip anyway, so this w [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string y2Sep {
            get {
                return ResourceManager.GetString("y2Sep", resourceCulture);
            }
        }
    }
}
